server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: @artifactId@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      username: ${USER:postgres}
      password: ${PWD:postgres}
      url: jdbc:postgresql://192.168.254.202:5432/xzqh